sudo: required
services:
  - docker

before_install:
  - docker build -t amenellah/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true amenellah/react-test npm test

after_success:
  - docker build -t amenellah/multi-client ./client
  - docker build -t amenellah/multi-nginx ./nginx
  - docker build -t amenellah/multi-server ./server
  - docker build -t amenellah/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push this images to dockerhub
  - docker push amenellah/multi-client
  - docker push amenellah/multi-nginx
  - docker push amenellah/multi-server
  - docker push amenellah/multi-worker

